# Generated by Django 2.2.5 on 2019-10-23 09:53

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0008_auto_20190926_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.AddField(
            model_name='message',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='anonymous', max_length=250, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
