# Generated by Django 2.2.5 on 2019-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0010_auto_20191023_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='mxh-cp-stories', max_length=200, verbose_name='作者'),
        ),
    ]
